<?php
return array(
'root'                       => array('Dir'  , '.'),
'index'                      => array('File' , 'index.php'),

'Experiments'                => array('Dir'  , 'Experiments'),
  'Common'                   => array('Dir'  , 'Experiments/_Common'),
    'Common Settings'        => array('File' , 'Experiments/_Common/Common Settings.json'),
    'Password'               => array('File' , 'Experiments/_Common/Password.php'),
    'Ineligibility Dir'      => array('Dir'  , 'Experiments/_Common/Ineligible'),
    'Media Dir'              => array('Dir'  , 'Experiments/_Common/Media'),
    'Media'                  => array('---'  , 'Experiments/_Common/Media/[var]'),
    'Custom Trial Types'     => array('Dir'  , 'Experiments/_Common/TrialTypes'),
    'Custom Trial Type Dir'  => array('Dir'  , 'Experiments/_Common/TrialTypes/[var]'),
      'Custom Trial Display' => array('File' , 'Experiments/_Common/TrialTypes/[var]/display.php'),
      'Custom Trial Helper'  => array('File' , 'Experiments/_Common/TrialTypes/[var]/helper.inc'),
      'Custom Trial Scoring' => array('File' , 'Experiments/_Common/TrialTypes/[var]/scoring.php'),
      'Custom Trial Script'  => array('File' , 'Experiments/_Common/TrialTypes/[var]/script.js'),
      'Custom Trial Style'   => array('File' , 'Experiments/_Common/TrialTypes/[var]/style.css'),
      'Custom Trial Validator'=>array('File' , 'Experiments/_Common/TrialTypes/[var]/validator.php'),

  'Current Experiment'       => array('Dir'  , 'Experiments/[Current Experiment]'),
    'Current Index'            => array('File' , 'Experiments/[Current Experiment]/index.php'),
    'Current Return'           => array('File' , 'Experiments/[Current Experiment]/Return.php'),
    'Conditions'               => array('CSV'  , 'Experiments/[Current Experiment]/Conditions.csv'),
    'Experiment Settings'      => array('File' , 'Experiments/[Current Experiment]/Settings.json'),
    'Stimuli Dir'              => array('Dir'  , 'Experiments/[Current Experiment]/Stimuli'),
      'Stimuli'                => array('CSV'  , 'Experiments/[Current Experiment]/Stimuli/[Stimuli]'),
    'Procedure Dir'            => array('Dir'  , 'Experiments/[Current Experiment]/Procedure'),
      'Procedure'              => array('CSV'  , 'Experiments/[Current Experiment]/Procedure/[Procedure]'),

'Code'                       => array('Dir'  , 'Code'),
  'Welcome'                  => array('File' , 'Code/Welcome.php'),
  'Custom Functions'         => array('File' , 'Code/customFunctions.php'),
  'Login'                    => array('File' , 'Code/login.php'),
  'Experiment Page'          => array('File' , 'Code/Experiment.php'),
  'Footer'                   => array('File' , 'Code/footer.php'),
  'Header'                   => array('File' , 'Code/header.php'),
  'Icon'                     => array('File' , 'Code/icon.png'),
  'Initiate Collector'       => array('File' , 'Code/initiateCollector.php'),
  'Trial Validator Require'  => array('File' , 'Code/trialValidator.require.php'),
  'No JS'                    => array('File' , 'Code/nojs.php'),
  'Set Password'             => array('File' , 'Code/setPassword.php'),
  'Shuffle Functions'        => array('File' , 'Code/shuffleFunctions.php'),
  'Custom Functions'         => array('File' , 'Code/customFunctions.php'),

  'CSS Dir'                  => array('Dir'  , 'Code/css'),
    'Global CSS'             => array('File' , 'Code/css/global.css'),
    'Jquery UI CSS'          => array('File' , 'Code/css/jquery-ui.min.css'),
    'Jquery UI Custom CSS'   => array('File' , 'Code/css/jquery-ui-1.10.4.custom.min.css'),
    'No JS Warning'          => array('File' , 'Code/css/nojswarning.png'),
    'Tools CSS'              => array('File' , 'Code/css/tools.css'),
    'Tutorial CSS'           => array('File' , 'Code/css/tutorial.css'),
    'Fonts'                  => array('Dir'  , 'Code/css/fonts'),
    'CSS Images'             => array('Dir'  , 'Code/css/images'),

  'Classes'                  => array('Dir'  , 'Code/classes'),
    'Conditions Class'       => array('File' , 'Code/classes/ConditionController.php'),
    'Control Files Class'    => array('File' , 'Code/classes/ControlFile.php'),
    'Debug Class'            => array('File' , 'Code/classes/DebugController.php'),
    'Errors Class'           => array('File' , 'Code/classes/ErrorController.php'),
    'Procedure Class'        => array('File' , 'Code/classes/Procedure.php'),
    'SideData Class'         => array('File' , 'Code/classes/SideData.php'),
    'Status Class'           => array('File' , 'Code/classes/StatusController.php'),
    'Stimuli Class'          => array('File' , 'Code/classes/Stimuli.php'),
    'system map'             => array('File' , 'Code/classes/systemMap.php'),

  'JS Dir'                   => array('Dir'  , 'Code/javascript'),
    'Collector JS'           => array('File' , 'Code/javascript/Collector.js'),
    'Jquery'                 => array('File' , 'Code/javascript/jquery.js'),
    'Jquery UI Custom'       => array('File' , 'Code/javascript/jquery-ui-1.10.4.custom.min.js'),
    'Jquery UI'              => array('File' , 'Code/javascript/jquery-1.12.4.min.js'),
    'Login JS'               => array('File' , 'Code/javascript/loggingIn.js'),
    'Sha256 JS'              => array('File' , 'Code/javascript/sha256.js'),

'Data'                       => array('Dir'  , 'Data'),
  'Session Dir'              => array('Dir'  , 'Data/sess'),
    'Session'                => array('Sess' , 'Data/sess/sess_[Session ID]'),
    'PHP Session Table'      => array('JSON' , 'Data/sess/session_table.json'),
  'Current Data Dir'         => array('Dir'  , 'Data/[Current Experiment]-Data[Data Sub Dir]'),
    'User Data'              => array('JSON' , 'Data/[Current Experiment]-Data[Data Sub Dir]/UserData/[Username].json'),
    'Random Assignments'     => array('File' , 'Data/[Current Experiment]-Data[Data Sub Dir]/RandomAssignments.txt'),
    'Status Begin Data'      => array('CSV'  , 'Data/[Current Experiment]-Data[Data Sub Dir]/Status_Begin.csv'),
    'Status End Data'        => array('CSV'  , 'Data/[Current Experiment]-Data[Data Sub Dir]/Status_End.csv'),
    'SideData Data'          => array('CSV'  , 'Data/[Current Experiment]-Data[Data Sub Dir]/SideData.csv'),
    'Output Dir'             => array('Dir'  , 'Data/[Current Experiment]-Data[Data Sub Dir]/Output'),
      'Output'               => array('CSV'  , 'Data/[Current Experiment]-Data[Data Sub Dir]/Output/[Username].csv'),

'Admin'                      => array('Dir'  , 'Admin'),
  'Admin Index'              => array('File' , 'Admin/index.php'),
  'Tools'                    => array('Dir'  , 'Admin/Tools'),

'Trial Types'                => array('Dir'  , 'TrialTypes'),
  'Trial Type Dir'           => array('Dir'  , 'TrialTypes/[var]'),
    'Trial Display'          => array('File' , 'TrialTypes/[var]/display.php'),
    'Trial Helper'           => array('File' , 'TrialTypes/[var]/helper.php'),
    'Trial Scoring'          => array('File' , 'TrialTypes/[var]/scoring.php'),
    'Trial Script'           => array('File' , 'TrialTypes/[var]/script.js'),
    'Trial Style'            => array('File' , 'TrialTypes/[var]/style.css'),
    'Trial Validator'        => array('File' , 'TrialTypes/[var]/validator.php'),
  'default helper'           => array('File' , 'TrialTypes/defaultTrialHelper.php'),
  'default scoring'          => array('File' , 'TrialTypes/defaultTrialScoring.php'),
);
